/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagementsystem.nour;

import java.awt.Color;

/**
 *
 * @author afifi.store
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
setLocationRelativeTo(null); // يفتح الفورم في النص

// 🎯 الخلفية العامة
getContentPane().setBackground(new java.awt.Color(18, 18, 18));

// 🏷️ إعدادات العنوان (Welcome)
lblWelcome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
lblWelcome.setForeground(new java.awt.Color(0, 204, 255));
lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
lblWelcome.setText("Welcome to Student Management System");

// 🧾 إعدادات الـ Labels (Username + Password)
jLabel1.setForeground(new java.awt.Color(230, 230, 230));
jLabel2.setForeground(new java.awt.Color(230, 230, 230));
jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));

// 🖊️ حقل Username
txtUser.setBackground(new java.awt.Color(35, 35, 35));
txtUser.setForeground(new java.awt.Color(0, 255, 255));
txtUser.setCaretColor(new java.awt.Color(0, 255, 255));
txtUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
));

// 🔒 حقل Password
txtPass.setBackground(new java.awt.Color(35, 35, 35));
txtPass.setForeground(new java.awt.Color(255, 255, 255));
txtPass.setCaretColor(new java.awt.Color(255, 200, 0));
txtPass.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
));

// 🔘 زر تسجيل الدخول
btnLogin.setBackground(new java.awt.Color(0, 204, 255));
btnLogin.setForeground(Color.BLACK);
btnLogin.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
btnLogin.setFocusPainted(false);
btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

// ✨ تأثير Hover على الزر (لون عند المرور بالماوس)
btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnLogin.setBackground(new java.awt.Color(0, 230, 255));
    }

    @Override
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnLogin.setBackground(new java.awt.Color(0, 204, 255));
    }
});



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UserName :");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 110, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password :");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 110, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWelcome.setText("Welcome StudentManagementSystem");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(lblWelcome, gridBagConstraints);

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 27, 27, 17);
        getContentPane().add(btnLogin, gridBagConstraints);

        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 258;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        getContentPane().add(txtUser, gridBagConstraints);

        txtPass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 258;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        getContentPane().add(txtPass, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // TODO add your handling code here:
        
                                           

    // 🧠 جلب القيم من الحقول
    String user = txtUser.getText().trim();
    String pass = new String(txtPass.getPassword()).trim();

    // ✅ تحقق من اسم المستخدم وكلمة المرور
    if (user.equals("admin") && pass.equals("1234")) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Login Successful!", 
            "Access Granted", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // اغلاق شاشة الدخول وفتح الرئيسية
        this.dispose();
        new MainForm().setVisible(true);

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Invalid Username or Password!", 
            "Access Denied", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }


        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
