/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagementsystem.nour;

import com.mycompany.studentmanagementsystem.SearchAndUpdate;
import com.mycompany.studentmanagementsystem.ViewStudents;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author afifi.store
 */
public class MainFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel mainPanel;
    private LoginPanel loginPanel;
    private Mainpanel homePanel;
    private ViewStudents viewStudentsPanel;
    private SearchAndUpdate searchAndUpdatePanel;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     *
     * @throws java.io.FileNotFoundException
     */
    public MainFrame() throws FileNotFoundException {
        initComponents();
        setTitle("🎓 Student Management System");

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        getContentPane().setBackground(new Color(240, 242, 245));

        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        mainPanel.setBackground(new Color(250, 250, 250));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        loginPanel = new LoginPanel();
        mainPanel.add(loginPanel, "login");

        homePanel = new Mainpanel(this);
        mainPanel.add(homePanel, "home");

        viewStudentsPanel = new ViewStudents(this);
        mainPanel.add(viewStudentsPanel, "viewStudents");

        searchAndUpdatePanel = new SearchAndUpdate(this);
        mainPanel.add(searchAndUpdatePanel, "searchAndUpdate");

        loginPanel.getLoginButton().addActionListener(e -> {
            String username = loginPanel.getUsername();
            String password = loginPanel.getPassword();

            if (username.equals("admin") && password.equals("1234")) {
                cardLayout.show(mainPanel, "home");
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Invalid username or password!",
                        "Login Failed",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
        );

        add(mainPanel, BorderLayout.CENTER);
        cardLayout.show(mainPanel, "login");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainFrame().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }
    
        /**
     * @return the homePanel
     */
    public Mainpanel getHomePanel() {
        return homePanel;
    }

    /**
     * @return the viewStudentsPanel
     */
    public ViewStudents getViewStudentsPanel() {
        return viewStudentsPanel;
    }

    /**
     * @return the searchAndUpdatePanel
     */
    public SearchAndUpdate getSearchAndUpdatePanel() {
        return searchAndUpdatePanel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
