/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import com.mycompany.studentmanagementsystem.database.StudentDatabase;
import com.mycompany.studentmanagementsystem.inputverifiers.IsAlphabeticVerifier;
import com.mycompany.studentmanagementsystem.inputverifiers.IsUniqueIdVerifier;
import com.mycompany.studentmanagementsystem.nour.MainFrame;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hazem
 */
public class AddStudent extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private StudentDatabase database;
    private String fullName;
    private String studentId;
    private int age = 1;
    private double GPA = 0;
    private String department;
    private String gender = "male";
    private boolean automateId = false;
    private IsAlphabeticVerifier nameVerifier = new IsAlphabeticVerifier("Name");
    private IsAlphabeticVerifier departmentVerifier = new IsAlphabeticVerifier("Department");
    private IsUniqueIdVerifier idVerifier;
    /**
     * Creates new form AddStudent
     * @param mainFrame
     * @throws java.io.FileNotFoundException
     */
    public AddStudent(MainFrame mainFrame) throws FileNotFoundException {
        this.mainFrame = mainFrame;
        initComponents();
        try
        {
            database = new StudentDatabase("students.txt");
            database.readFromFile();
            idVerifier = new IsUniqueIdVerifier(database);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            showHome();
        }
        btnMale.setSelected(true);
        fieldFullName.setInputVerifier(nameVerifier);
        fieldDepartment.setInputVerifier(departmentVerifier);
        fieldStudentId.setInputVerifier(idVerifier);
        
        showHome.setVerifyInputWhenFocusTarget(false); //very very important if you are willing to use inputVerifiers
        btnAutomateId.setVerifyInputWhenFocusTarget(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        genderBtn = new javax.swing.ButtonGroup();
        showHome = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelFullName = new javax.swing.JLabel();
        labelStudentId = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelGPA = new javax.swing.JLabel();
        labelDepartment = new javax.swing.JLabel();
        fieldFullName = new javax.swing.JTextField();
        btnAutomateId = new javax.swing.JRadioButton();
        fieldStudentId = new javax.swing.JTextField();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        fieldDepartment = new javax.swing.JTextField();
        spinnerAge = new javax.swing.JSpinner();
        spinnerGPA = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridBagLayout());

        showHome.setBackground(new java.awt.Color(49, 51, 53));
        showHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showHome.setText(" ← Back ");
        showHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showHome.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showHome.setOpaque(true);
        showHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(showHome, gridBagConstraints);

        Title.setBackground(new java.awt.Color(49, 51, 53));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Add Student");
        Title.setToolTipText("");
        Title.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title.setMaximumSize(new java.awt.Dimension(67, 25));
        Title.setMinimumSize(new java.awt.Dimension(67, 25));
        Title.setOpaque(true);
        Title.setPreferredSize(new java.awt.Dimension(67, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 553;
        gridBagConstraints.ipady = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 72, 0, 2);
        add(Title, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(49, 51, 53));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelFullName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelFullName.setText("Full Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 71, 0, 0);
        jPanel1.add(labelFullName, gridBagConstraints);

        labelStudentId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelStudentId.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 71, 0, 0);
        jPanel1.add(labelStudentId, gridBagConstraints);

        labelAge.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelAge.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 71, 0, 0);
        jPanel1.add(labelAge, gridBagConstraints);

        labelGender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelGender.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 88;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 71, 0, 0);
        jPanel1.add(labelGender, gridBagConstraints);

        labelGPA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelGPA.setText("GPA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 71, 0, 0);
        jPanel1.add(labelGPA, gridBagConstraints);

        labelDepartment.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelDepartment.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 71, 0, 0);
        jPanel1.add(labelDepartment, gridBagConstraints);

        fieldFullName.setBackground(new java.awt.Color(255, 255, 255));
        fieldFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldFullName.setForeground(new java.awt.Color(0, 0, 0));
        fieldFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldFullName.setFocusTraversalPolicyProvider(true);
        fieldFullName.setNextFocusableComponent(fieldStudentId);
        fieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFullNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 341;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(fieldFullName, gridBagConstraints);

        btnAutomateId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAutomateId.setText("Automate ID");
        btnAutomateId.setFocusTraversalPolicyProvider(true);
        btnAutomateId.setNextFocusableComponent(btnMale);
        btnAutomateId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomateIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(24, 48, 0, 0);
        jPanel1.add(btnAutomateId, gridBagConstraints);

        fieldStudentId.setBackground(new java.awt.Color(255, 255, 255));
        fieldStudentId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldStudentId.setForeground(new java.awt.Color(0, 0, 0));
        fieldStudentId.setFocusTraversalPolicyProvider(true);
        fieldStudentId.setNextFocusableComponent(btnMale);
        fieldStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStudentIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 6, 0, 0);
        jPanel1.add(fieldStudentId, gridBagConstraints);

        genderBtn.add(btnMale);
        btnMale.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMale.setText("Male");
        btnMale.setFocusTraversalPolicyProvider(true);
        btnMale.setNextFocusableComponent(spinnerAge);
        btnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(btnMale, gridBagConstraints);

        genderBtn.add(btnFemale);
        btnFemale.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFemale.setText("Female");
        btnFemale.setFocusTraversalPolicyProvider(true);
        btnFemale.setNextFocusableComponent(spinnerAge);
        btnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemaleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(24, 48, 0, 0);
        jPanel1.add(btnFemale, gridBagConstraints);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 593;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 8, 5, 8);
        jPanel1.add(btnAdd, gridBagConstraints);

        fieldDepartment.setBackground(new java.awt.Color(255, 255, 255));
        fieldDepartment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldDepartment.setForeground(new java.awt.Color(0, 0, 0));
        fieldDepartment.setFocusTraversalPolicyProvider(true);
        fieldDepartment.setNextFocusableComponent(spinnerGPA);
        fieldDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDepartmentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 341;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 6, 0, 0);
        jPanel1.add(fieldDepartment, gridBagConstraints);

        spinnerAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerAge.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spinnerAge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spinnerAge.setFocusTraversalPolicyProvider(true);
        spinnerAge.setNextFocusableComponent(fieldDepartment);
        spinnerAge.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAgeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 314;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 0);
        jPanel1.add(spinnerAge, gridBagConstraints);

        spinnerGPA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerGPA.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 4.0d, 0.01d));
        spinnerGPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spinnerGPA.setFocusTraversalPolicyProvider(true);
        spinnerGPA.setNextFocusableComponent(fieldFullName);
        spinnerGPA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerGPAStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 341;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 6, 0, 0);
        jPanel1.add(spinnerGPA, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 4, 0);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void showHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHomeActionPerformed
        // TODO add your handling code here:
        showHome();
    }//GEN-LAST:event_showHomeActionPerformed

    private void fieldDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDepartmentActionPerformed
        // TODO add your handling code here:
        if(departmentVerifier.verify(fieldDepartment))
        {
            this.department = fieldDepartment.getText();
            spinnerGPA.requestFocus();
        }
        else
        {
            fieldDepartment.requestFocus();
        }
    }//GEN-LAST:event_fieldDepartmentActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        boolean successfullStudentAppend = false;
        int confirmationResponse;
        try
        {
            confirmationResponse = JOptionPane.showConfirmDialog(this, "Do you want to add this student?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
        }catch(Exception e)
        {
            return;
        }
        if(confirmationResponse!=JOptionPane.YES_OPTION)
        {
            return;
        }
        
        try 
        {
            database.readFromFile();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            showHome();
        }

        if( nameVerifier.verify(fieldFullName)&&
            departmentVerifier.verify(fieldDepartment))
        {
            this.fullName = fieldFullName.getText();
            this.department = fieldDepartment.getText();
            if(this.automateId)
            {
                database.addStudent(fullName, age, gender, department, GPA);
                successfullStudentAppend =true;
            }
            else if(idVerifier.verify(fieldStudentId))
            {
                this.studentId = fieldStudentId.getText();
                database.addStudent(Integer.parseInt(studentId), fullName, age, gender, department, GPA);
                successfullStudentAppend =true;
            }
            
        }
        try {
            database.saveToFile();
            if(successfullStudentAppend ==true)
            {
                JOptionPane.showMessageDialog(this, "Student has been added successfully","Successful Operation!", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            showHome();
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemaleActionPerformed
        // TODO add your handling code here:
        if(btnFemale.isSelected())
        {
            this.gender="female";
        }
        else
        {
            this.gender ="male";
        }
    }//GEN-LAST:event_btnFemaleActionPerformed

    private void btnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaleActionPerformed
        // TODO add your handling code here:
        if(btnMale.isSelected())
        {
            this.gender="male";
        }
        else
        {
            this.gender ="female";
        }
    }//GEN-LAST:event_btnMaleActionPerformed

    private void fieldStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStudentIdActionPerformed
        // TODO add your handling code here:
        if(idVerifier.verify(fieldStudentId))
        {
            this.studentId = fieldStudentId.getText();
            btnMale.requestFocus();
        }
        else
        {
            fieldStudentId.requestFocus();
        }
    }//GEN-LAST:event_fieldStudentIdActionPerformed

    private void fieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFullNameActionPerformed
        // TODO add your handling code here:
        if(nameVerifier.verify(fieldFullName))
        {
            this.fullName = fieldFullName.getText();
            fieldStudentId.requestFocus();
        }
        else
        {
            fieldFullName.requestFocus();
        }
    }//GEN-LAST:event_fieldFullNameActionPerformed

    private void btnAutomateIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomateIdActionPerformed
        // TODO add your handling code here:
        fieldStudentId.setVisible(!btnAutomateId.isSelected());
        automateId = btnAutomateId.isSelected();
    }//GEN-LAST:event_btnAutomateIdActionPerformed

    private void spinnerAgeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAgeStateChanged
        // TODO add your handling code here:
        this.age = (int)spinnerAge.getValue();
    }//GEN-LAST:event_spinnerAgeStateChanged

    private void spinnerGPAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerGPAStateChanged
        // TODO add your handling code here:
        this.GPA = (double)spinnerGPA.getValue();
    }//GEN-LAST:event_spinnerGPAStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAdd;
    private javax.swing.JRadioButton btnAutomateId;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JTextField fieldDepartment;
    private javax.swing.JTextField fieldFullName;
    private javax.swing.JTextField fieldStudentId;
    private javax.swing.ButtonGroup genderBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelDepartment;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JLabel labelGPA;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelStudentId;
    private javax.swing.JButton showHome;
    private javax.swing.JSpinner spinnerAge;
    private javax.swing.JSpinner spinnerGPA;
    // End of variables declaration//GEN-END:variables

    public final void showHome() {
        mainFrame.getCardLayout().show(mainFrame.getMainPanel(), "home");
    }
}
