/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import com.mycompany.studentmanagementsystem.Shared.FormatTable;
import com.mycompany.studentmanagementsystem.Shared.IconUtils;
import com.mycompany.studentmanagementsystem.Shared.LoadData;
import com.mycompany.studentmanagementsystem.Shared.SwitchPanels;
import com.mycompany.studentmanagementsystem.database.StudentDatabase;
import com.mycompany.studentmanagementsystem.nour.MainFrame;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mega
 */
public final class SearchAndUpdate extends javax.swing.JPanel {

    private MainFrame mainFrame; // Add this field
    private final Color originalSelectionColor;
    private boolean isHighlighted = false;
    private int editingModelRow = -1;
    private final StudentDatabase studentDatabase;
    DefaultTableModel model;

    /**
     * Creates new form SearchAndUpdate
     *
     * @param mainFrame
     * @throws java.io.FileNotFoundException
     */
    public SearchAndUpdate(MainFrame mainFrame) throws FileNotFoundException {
        this.mainFrame = mainFrame;
        initComponents();
        studentDatabase = new StudentDatabase("students.txt");
        studentDatabase.readFromFile();
        this.model = (DefaultTableModel) students.getModel();
        LoadData.loadStudentsIntoTable(studentDatabase.returnAllStudents(), model);
        originalSelectionColor = students.getSelectionBackground();
        ImageIcon searchIcon = new ImageIcon(
                getClass().getResource("/search.png"));
        ImageIcon SearchSmallIcon = IconUtils.resizeIcon(searchIcon, 24, 24);
        search.setIcon(SearchSmallIcon);

        ImageIcon updateIcon = new ImageIcon(
                getClass().getResource("/updated.png"));
        ImageIcon UpdateSmallIcon = IconUtils.resizeIcon(updateIcon, 24, 24);
        updateButton.setIcon(UpdateSmallIcon);

        FormatTable.center(students);

        FormatTable.customizeSorter(students);

        this.updateForm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        students = new javax.swing.JTable();
        updateForm = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        gpa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 100, 10, 300, 10};
        layout.rowHeights = new int[] {80, 10, 100, 10};
        layout.columnWeights = new double[] {0.023, 0.23, 0.023, 0.697};
        layout.rowWeights = new double[] {0.0, 0.05, 0.5, 0.05};
        setLayout(layout);

        jScrollPane1.setBackground(new java.awt.Color(49, 51, 53));
        jScrollPane1.setForeground(new java.awt.Color(49, 51, 53));

        students.setBackground(new java.awt.Color(49, 51, 53));
        students.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        students.setForeground(new java.awt.Color(255, 255, 255));
        students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                { new Integer(101), "Mohamed Hassan",  new Integer(23), "Male", "CSE", null}
            },
            new String [] {
                "ID", "Full Name", "Age", "Gender", "Department", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        students.setAutoscrolls(false);
        students.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        students.setRowHeight(40);
        students.setSelectionBackground(new java.awt.Color(30, 30, 30));
        students.setShowGrid(true);
        students.getTableHeader().setReorderingAllowed(false);
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(students);
        students.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jScrollPane1, gridBagConstraints);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {50, 5, 100, 10, 50, 5, 100};
        jPanel1Layout.rowHeights = new int[] {50, 5, 50, 5, 50, 5, 50, 5};
        jPanel1Layout.columnWeights = new double[] {0.156, 0.0156, 0.3125, 0.03125, 0.156, 0.0156, 0.3125};
        jPanel1Layout.rowWeights = new double[] {0.3125, 0.03125, 0.3125, 0.03125, 0.3125};
        updateForm.setLayout(jPanel1Layout);

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(id, gridBagConstraints);

        fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(fullName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(age, gridBagConstraints);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(gender, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(gpa, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Full name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("GPA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(jLabel5, gridBagConstraints);

        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(department, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(jLabel6, gridBagConstraints);

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        updateForm.add(updateButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(updateForm, gridBagConstraints);

        java.awt.GridBagLayout jPanel1Layout1 = new java.awt.GridBagLayout();
        jPanel1Layout1.columnWidths = new int[] {35, 5, 75, 5, 290};
        jPanel1.setLayout(jPanel1Layout1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(searchField, gridBagConstraints);

        search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(search, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(49, 51, 53));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText(" ← Back ");
        jButton1.setBorder(null);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameActionPerformed

    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
        // TODO add your handling code here:
        int viewRow = students.rowAtPoint(evt.getPoint());
        int modelRow = students.convertRowIndexToModel(viewRow);

        Integer id = (Integer) model.getValueAt(modelRow, 0);
        String fullName = model.getValueAt(modelRow, 1).toString();
        Integer age = (Integer) model.getValueAt(modelRow, 2);
        String gender = model.getValueAt(modelRow, 3).toString();
        String department = model.getValueAt(modelRow, 4).toString();
        Double gpa = (Double) model.getValueAt(modelRow, 5);

        loadUpdateForm(id, fullName, age, gender, department, gpa);
        editingModelRow = modelRow;
    }//GEN-LAST:event_studentsMouseClicked

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String key = searchField.getText();
        searchAndHighlight(key);

    }//GEN-LAST:event_searchActionPerformed


    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            // TODO add your handling code here:
            update(editingModelRow);
        } catch (Exception ex) {
            Logger.getLogger(SearchAndUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SwitchPanels.showHome(mainFrame);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadUpdateForm(int id, String fullName, int age, String gender, String department, double gpa) {
        // 1. Fill the form fields
        this.id.setText(String.valueOf(id));
        this.fullName.setText(fullName);
        this.age.setText(String.valueOf(age));
        this.department.setText(department);
        this.gpa.setText(String.valueOf(gpa));
        this.gender.setSelectedItem(gender);
        updateForm.setVisible(true);

        // 3. Optional: Scroll to the form if your panel is tall
        revalidate();
        repaint();
    }

    private void update(int modelRow) throws Exception {
        int id = Integer.parseInt(this.id.getText());
        String fullName = this.fullName.getText();
        int age = Integer.parseInt(this.age.getText());
        String gender = this.gender.getSelectedItem().toString();
        String department = this.department.getText();
        double gpa = Double.parseDouble(this.gpa.getText());

        model.setValueAt(id, modelRow, 0);
        model.setValueAt(fullName, modelRow, 1);
        model.setValueAt(age, modelRow, 2);
        model.setValueAt(gender, modelRow, 3);
        model.setValueAt(department, modelRow, 4);
        model.setValueAt(gpa, modelRow, 5);

        studentDatabase.editStudentById(id, fullName, age, gender, department, gpa);
        studentDatabase.saveToFile();
    }

    private void searchAndHighlight(String term) {
        if (term == null || term.trim().isEmpty()) {
            if (isHighlighted) {
                students.setSelectionBackground(originalSelectionColor);
                students.clearSelection();
                isHighlighted = false;
            }
            return;
        }

        TableModel model = students.getModel();
        for (int modelRow = 0; modelRow < model.getRowCount(); modelRow++) {
            Integer id = (Integer) model.getValueAt(modelRow, 0);
            String name = (String) model.getValueAt(modelRow, 1);

            if (term.equals(String.valueOf(id))
                    || (name != null && name.toLowerCase().equals(term.toLowerCase()))) {

                // highlight using cutom color
                students.setSelectionBackground(new Color(98, 151, 85));
                int viewRow = students.convertRowIndexToView(modelRow);
                students.setRowSelectionInterval(viewRow, viewRow);
                students.scrollRectToVisible(students.getCellRect(viewRow, 0, true));
                isHighlighted = true;
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Not found");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField department;
    private javax.swing.JTextField fullName;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField gpa;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable students;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updateForm;
    // End of variables declaration//GEN-END:variables

}
