/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import com.mycompany.studentmanagementsystem.database.StudentDatabase;
import com.mycompany.studentmanagementsystem.nour.MainFrame;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mega
 */
public final class ViewStudents extends javax.swing.JPanel {

    private MainFrame mainFrame; // Add this field
    private final StudentDatabase studentDatabase;
    DefaultTableModel model;

    /**
     * Creates new form ViewStudents
     *
     * @param mainFrame
     * @throws java.io.FileNotFoundException
     */
    public ViewStudents(MainFrame mainFrame) throws FileNotFoundException {
        this.mainFrame = mainFrame; // Store the reference
        initComponents();
        studentDatabase = new StudentDatabase("students.txt");
        studentDatabase.readFromFile();
        this.model = (DefaultTableModel) students.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

        loadStudentsIntoTable(studentDatabase.returnAllStudents());
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Apply to all columns
        for (int i = 0; i < students.getColumnCount(); i++) {
            students.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // 1. Create a custom sorter
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(students.getModel());

        // 2. Configure it
        sorter.setSortable(0, true);   // ID
        sorter.setSortable(1, true);   // Name
        sorter.setSortable(2, false);  // Age
        sorter.setSortable(3, false);  // Gender
        sorter.setSortable(4, false);  // Department
        sorter.setSortable(5, true);  // GPA
        students.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        students = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 200, 10};
        layout.rowHeights = new int[] {80, 10, 100, 10};
        layout.columnWeights = new double[] {0.45, 0.9, 0.45};
        layout.rowWeights = new double[] {0.0, 0.05, 0.5, 0.05};
        setLayout(layout);

        jScrollPane1.setBackground(new java.awt.Color(49, 51, 53));
        jScrollPane1.setForeground(new java.awt.Color(49, 51, 53));

        students.setBackground(new java.awt.Color(49, 51, 53));
        students.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        students.setForeground(new java.awt.Color(255, 255, 255));
        students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Age", "Gender", "Department", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        students.setAutoscrolls(false);
        students.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        students.setRowHeight(40);
        students.setSelectionBackground(new java.awt.Color(30, 30, 30));
        students.setShowGrid(true);
        students.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(students);
        students.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jScrollPane1, gridBagConstraints);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {10, 210};
        jPanel1Layout.columnWeights = new double[] {0.0, 1.0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setBackground(new java.awt.Color(49, 51, 53));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Students : ");
        jLabel1.setMaximumSize(new java.awt.Dimension(121, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(121, 50));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(121, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 356;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(jLabel1, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(49, 51, 53));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText(" ← Back ");
        jButton1.setBorder(null);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showHome();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void loadStudentsIntoTable(ArrayList<Student> studentList) {
        // 1. Get the table model

        // 2. Clear existing rows
        model.setRowCount(0);

        // 3. Add each student as a row
        for (Student s : studentList) {
            Object[] row = {
                s.getStudentId(),
                s.getFullName(),
                s.getAge(),
                s.getGender(),
                s.getDepartment(),
                s.getGPA()
            };
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable students;
    // End of variables declaration//GEN-END:variables

    public void showHome() {
        mainFrame.getCardLayout().show(mainFrame.getMainPanel(), "home");
    }

}
